table dim_date
	dataCategory: Time

	column asof
		dataType: dateTime
		formatString: dd mmm yyyy
		isKey
		summarizeBy: none
		sourceColumn: asof

	column month
		dataType: string
		sortByColumn: month_index
		summarizeBy: none
		sourceColumn: month

	column month_index
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: month_index

	column is_latest
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_latest

	partition dim_date = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				Typed = Table.TransformColumnTypes(Promoted, {{"asof", type date}, {"month", type text}, {"month_index", Int64.Type}, {"is_latest", type logical}}, "en-US")
			in
				Typed
