table fact_ipv

	column asof
		dataType: dateTime
		formatString: dd mmm yyyy
		summarizeBy: none
		sourceColumn: asof

	column position_id
		dataType: string
		summarizeBy: none
		sourceColumn: position_id

	column derived_level
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: derived_level

	column desk_mark
		dataType: double
		formatString: #,##0.0000
		summarizeBy: none
		sourceColumn: desk_mark

	column consensus
		dataType: double
		formatString: #,##0.0000
		summarizeBy: none
		sourceColumn: consensus

	column n_quotes
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: n_quotes

	column variance_u
		dataType: double
		formatString: #,##0.00
		summarizeBy: none
		sourceColumn: variance_u

	column tolerance_u
		dataType: double
		formatString: #,##0.00
		summarizeBy: none
		sourceColumn: tolerance_u

	column tol_ratio
		dataType: double
		formatString: 0.00
		summarizeBy: none
		sourceColumn: tol_ratio

	column pv_adjustment_usd
		dataType: double
		formatString: #,##0
		summarizeBy: none
		sourceColumn: pv_adjustment_usd

	column ava_mpu_usd
		dataType: double
		formatString: #,##0
		summarizeBy: none
		sourceColumn: ava_mpu_usd

	column ava_coc_usd
		dataType: double
		formatString: #,##0
		summarizeBy: none
		sourceColumn: ava_coc_usd

	column quote_age_bd
		dataType: double
		formatString: 0
		summarizeBy: none
		sourceColumn: quote_age_bd

	column mark_age_periods
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: mark_age_periods

	column rule_flags
		dataType: string
		summarizeBy: none
		sourceColumn: rule_flags

	column anomaly_score
		dataType: double
		formatString: 0.000
		summarizeBy: none
		sourceColumn: anomaly_score

	column anomaly_flag
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: anomaly_flag

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status

	column severity
		dataType: string
		summarizeBy: none
		sourceColumn: severity

	column is_breach
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_breach

	partition fact_ipv = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/fact_ipv.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				Typed = Table.TransformColumnTypes(Promoted, {{"asof", type date}, {"position_id", type text}, {"derived_level", Int64.Type}, {"desk_mark", type number}, {"consensus", type number}, {"n_quotes", Int64.Type}, {"variance_u", type number}, {"tolerance_u", type number}, {"tol_ratio", type number}, {"pv_adjustment_usd", type number}, {"ava_mpu_usd", type number}, {"ava_coc_usd", type number}, {"quote_age_bd", type number}, {"mark_age_periods", Int64.Type}, {"rule_flags", type text}, {"anomaly_score", type number}, {"anomaly_flag", Int64.Type}, {"status", type text}, {"severity", type text}, {"is_breach", type logical}}, "en-US")
			in
				Typed
