table fact_control

	column asof
		dataType: dateTime
		formatString: dd mmm yyyy
		summarizeBy: none
		sourceColumn: asof

	column control
		dataType: string
		summarizeBy: none
		sourceColumn: control

	column scope
		dataType: string
		summarizeBy: none
		sourceColumn: scope

	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status

	column detail
		dataType: string
		summarizeBy: none
		sourceColumn: detail

	partition fact_control = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "/fact_control.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				Typed = Table.TransformColumnTypes(Promoted, {{"asof", type date}, {"control", type text}, {"scope", type text}, {"status", type text}, {"detail", type text}}, "en-US")
			in
				Typed
